#!/bin/zsh

# Tool name: hpc

export PYTHON_INTERPRETER="${HPC_TOOLS_DIR}/.venv/bin/python3"

# Command Aliases
alias sync_project_command="${PYTHON_INTERPRETER} ${HPC_TOOLS_DIR}/hpc_tools/sync_project.py"
alias run_command="${PYTHON_INTERPRETER} ${HPC_TOOLS_DIR}/hpc_tools/submit.py"
alias status_command="ssh Hilbert -t \"bash -ci 'base && clear && qs'\""
alias start_interactive_command="ssh Hilbert -t \"bash -ci 'base && clear && qi'\""
alias connect_to_logs_command="ssh Hilbert -t \"bash -ci 'base && clear && home && job_log'\""
alias sync_results_command="${PYTHON_INTERPRETER} ${HPC_TOOLS_DIR}/sync_results.py"

# Alias for syncing local huggingface models with HPC
alias sync_hf_command="rsync -avz --delete --progress ${HOME}/.cache/huggingface/ Hilbert-Storage:/gpfs/project/${ZIM_USERNAME}/models/huggingface"

sync_job_logs() {
    if [[ ! -d "${HOME}/Projects/hpc_job_logs" ]]; then
        mkdir -p "${HOME}/Projects/hpc_job_logs"
    fi

    rsync \
        -avz --delete --progress \
        "Hilbert:/gpfs/project/${ZIM_USERNAME}/job_logs/" \
        "${HOME}/Projects/hpc_job_logs"
}

# Function to display the usage of the tool
usage() {
    echo "Usage: hpc <command>"
    echo "Commands:"
    echo "  run   Run a python or bash script on the HPC"
    echo "  sync_project   Sync the local project with the HPC"
    echo "  sync_results   Sync the results from the HPC to the local machine"
    echo "  status   Check the status of the jobs and queues on the HPC"
    echo "  sync_job_logs   Sync the job logs from the HPC to the local machine"
    echo "  setup_interactive   Setup an interactive session on the HPC"
    echo "  ssh  Connect to the HPC Login node"
    echo "  qi  Start an interactive session on the HPC"
    echo "  sync_hf  Sync the local huggingface models with the HPC"
    echo "  log Connect to the logs of running jobs on the HPC"
    echo "  cmd  Run a command on the HPC Login node"
}

# Main script execution starts here
if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

COMMAND=$1
shift

case "$COMMAND" in
    run)
        sync_project_command &&
        run_command "$@"
        ;;
    sync_project)
        sync_project_command
        ;;
    sync_results)
        sync_results_command
        ;;
    status)
        status_command
        ;;
    sync_job_logs)
        sync_job_logs
        ;;
    setup_interactive)
        ssh Hilbert -t "bash -ci 'base && clear && qi-setup $@'"
        ;;
    ssh)
        ssh Hilbert
        ;;
    qi)
        start_interactive_command
        ;;
    log)
        connect_to_logs_command
        ;;
    sync_hf)
        sync_hf_command
        ;;
    cmd)
        ssh Hilbert -t "bash -ci '$@'"
        ;;
    *)
        echo "Error: Unknown command '$COMMAND'"
        usage
        exit 1
        ;;
esac
